/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.*;
import javax.swing.*;
import static project.Student.student;
import static project.Student.counter;


/**
 *
 * @author Star Goh
 */
public class Menu extends javax.swing.JFrame {

 
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFIle = new javax.swing.JMenu();
        SaveBTN = new javax.swing.JMenuItem();
        OpenBTN = new javax.swing.JMenuItem();
        ExitButton = new javax.swing.JMenuItem();
        MenuAdd = new javax.swing.JMenu();
        AddNewStudentButton = new javax.swing.JMenuItem();
        MenuPrint = new javax.swing.JMenu();
        PrintStudent = new javax.swing.JMenuItem();
        MenuSearch = new javax.swing.JMenu();
        SearchBTN = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();
        EditStudentBTN = new javax.swing.JMenuItem();
        MenuDelete = new javax.swing.JMenu();
        DeleteStudentBTN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Information System");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO STUDENT INFORMATION SYSTEM");

        MenuFIle.setText("File");

        SaveBTN.setText("Save");
        SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBTNActionPerformed(evt);
            }
        });
        MenuFIle.add(SaveBTN);

        OpenBTN.setText("Open");
        OpenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenBTNActionPerformed(evt);
            }
        });
        MenuFIle.add(OpenBTN);

        ExitButton.setText("Exit");
        ExitButton.setToolTipText("");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        MenuFIle.add(ExitButton);

        jMenuBar1.add(MenuFIle);

        MenuAdd.setText("Add");

        AddNewStudentButton.setText("Add New Student");
        AddNewStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewStudentButtonActionPerformed(evt);
            }
        });
        MenuAdd.add(AddNewStudentButton);

        jMenuBar1.add(MenuAdd);

        MenuPrint.setText("Print");

        PrintStudent.setText("Print Student Data");
        PrintStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintStudentActionPerformed(evt);
            }
        });
        MenuPrint.add(PrintStudent);

        jMenuBar1.add(MenuPrint);

        MenuSearch.setText("Search");

        SearchBTN.setText("Search Student Details");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });
        MenuSearch.add(SearchBTN);

        jMenuBar1.add(MenuSearch);

        MenuEdit.setText("Edit");

        EditStudentBTN.setText("Edit Student Data");
        EditStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditStudentBTNActionPerformed(evt);
            }
        });
        MenuEdit.add(EditStudentBTN);

        jMenuBar1.add(MenuEdit);

        MenuDelete.setText("Delete");

        DeleteStudentBTN.setText("Delete Student Data");
        DeleteStudentBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStudentBTNActionPerformed(evt);
            }
        });
        MenuDelete.add(DeleteStudentBTN);

        jMenuBar1.add(MenuDelete);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(79, 79, 79)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AddNewStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewStudentButtonActionPerformed

        new AddNewStudent().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewStudentButtonActionPerformed

    private void PrintStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintStudentActionPerformed

        new DisplayStudent().setVisible(true);

    }//GEN-LAST:event_PrintStudentActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed

        new SearchStudent().setVisible(true);
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void EditStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditStudentBTNActionPerformed

        new EditStudent().setVisible(true);
    }//GEN-LAST:event_EditStudentBTNActionPerformed

    private void DeleteStudentBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStudentBTNActionPerformed

        new DeleteStudent().setVisible(true);

    }//GEN-LAST:event_DeleteStudentBTNActionPerformed

    private void SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBTNActionPerformed
        try {
            File file = new File("dataFile.txt");
            FileWriter fw = new FileWriter(file);
            PrintWriter pw = new PrintWriter(fw);
            for (int i = 0; i < student.size(); i++) {
                pw.println(student.get(i).getMatric());
                pw.println(student.get(i).getName());
                pw.println(student.get(i).getcwMark());
                pw.println(student.get(i).getFinalMark());
                pw.println(student.get(i).getGrade());
                pw.println(student.get(i).getType());
                pw.println(student.get(i).getSVName());
            }
            pw.close();
            JOptionPane.showMessageDialog(null, " Student data has been saved in file.");

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error: File not found!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error: File write problem!");
        }


    }//GEN-LAST:event_SaveBTNActionPerformed

    private void OpenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenBTNActionPerformed

        JFileChooser chooser = new JFileChooser("C:/Users/USER/Documents/NetBeansProjects/");
        chooser.showOpenDialog(null);
        File myFile = chooser.getSelectedFile();

        try {
            FileReader fileReader = new FileReader(myFile);
            BufferedReader bufReader = new BufferedReader(fileReader);
            String Matric = bufReader.readLine();
            while (Matric != null) {
                int m = Integer.parseInt(Matric);
                String nama = bufReader.readLine();
                
                String cw = bufReader.readLine();
                
                double cwm = Double.parseDouble(cw);
                String finalm = bufReader.readLine();
                
                double fm = Double.parseDouble(finalm);
                String grade = bufReader.readLine();
                String studType = bufReader.readLine();
                String svName = bufReader.readLine();
                //int i = Integer.parseInt(bufReader.readLine());
                
                if (studType.equals("Undergraduate")){

                Student STUDE = new UndergraduateStudent(m, nama, cwm, fm, grade, studType, svName);

                student.add(STUDE);
                }
                
                else if (studType.equals("Postgraduate")){
                 Student STUDE = new PostgraduateStudent(m, nama, cwm, fm, grade, studType, svName);

                student.add(STUDE);   
                }
                

                Matric = bufReader.readLine();
            }
            bufReader.close();
            JOptionPane.showMessageDialog(null, " Student has been added in list.");

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error: File not found!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error: File read problem!");
        }

    }//GEN-LAST:event_OpenBTNActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddNewStudentButton;
    private javax.swing.JMenuItem DeleteStudentBTN;
    private javax.swing.JMenuItem EditStudentBTN;
    private javax.swing.JMenuItem ExitButton;
    private javax.swing.JMenu MenuAdd;
    private javax.swing.JMenu MenuDelete;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuFIle;
    private javax.swing.JMenu MenuPrint;
    private javax.swing.JMenu MenuSearch;
    private javax.swing.JMenuItem OpenBTN;
    private javax.swing.JMenuItem PrintStudent;
    private javax.swing.JMenuItem SaveBTN;
    private javax.swing.JMenuItem SearchBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
